<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-home',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2023-08-04 09:39:05',
                'updated_at' => '2023-09-11 07:30:51',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2023-08-04 09:39:05',
                'updated_at' => '2023-09-05 17:04:54',
                'route' => 'voyager.media.index',
                'parameters' => 'null',
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Usuários',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2023-08-04 09:39:05',
                'updated_at' => '2023-09-11 07:30:51',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2023-08-04 09:39:05',
                'updated_at' => '2023-09-11 07:30:51',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2023-08-04 09:39:05',
                'updated_at' => '2023-09-05 16:57:53',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2023-08-04 09:39:06',
                'updated_at' => '2023-08-06 17:49:25',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2023-08-04 09:39:06',
                'updated_at' => '2023-08-06 17:49:25',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2023-08-04 09:39:06',
                'updated_at' => '2023-08-06 17:49:25',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2023-08-04 09:39:06',
                'updated_at' => '2023-08-06 17:49:25',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2023-08-04 09:39:06',
                'updated_at' => '2023-09-05 16:57:53',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Rotas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 3,
                'created_at' => '2023-08-04 09:43:52',
                'updated_at' => '2023-09-11 07:31:16',
                'route' => 'voyager.rotas.index',
                'parameters' => 'null',
            ),
            11 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Estudantes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-star-half',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 2,
                'created_at' => '2023-08-04 10:13:51',
                'updated_at' => '2023-09-11 07:29:58',
                'route' => 'voyager.estudantes.index',
                'parameters' => 'null',
            ),
            12 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Motoristas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-smile',
                'color' => '#000000',
                'parent_id' => 25,
                'order' => 1,
                'created_at' => '2023-08-04 10:14:57',
                'updated_at' => '2023-09-11 07:32:08',
                'route' => 'voyager.motoristas.index',
                'parameters' => 'null',
            ),
            13 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Solicitações',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-skull',
                'color' => '#000000',
                'parent_id' => 26,
                'order' => 2,
                'created_at' => '2023-08-04 10:15:55',
                'updated_at' => '2023-09-11 07:35:05',
                'route' => 'voyager.solicitacaos.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Veículos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-truck',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 1,
                'created_at' => '2023-08-04 10:20:18',
                'updated_at' => '2023-08-06 18:36:32',
                'route' => 'voyager.veiculos.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Viagem',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-ticket',
                'color' => '#000000',
                'parent_id' => 26,
                'order' => 1,
                'created_at' => '2023-08-04 10:22:37',
                'updated_at' => '2023-09-11 07:36:01',
                'route' => 'voyager.viagems.index',
                'parameters' => 'null',
            ),
            16 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Cadastros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-logbook',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2023-08-06 17:49:09',
                'updated_at' => '2023-09-05 16:57:46',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Perfis',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2023-08-06 17:49:22',
                'updated_at' => '2023-09-05 16:57:46',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Serviços',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2023-08-06 17:50:12',
                'updated_at' => '2023-09-05 16:57:46',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}